### ISSUE TITLE
Annotation query failed

### ISSUE THREAD

**Issue by abl73** [kernelkaribou/synology-monitoring#15] opened 2020-07-08 17:30 UTC
Followed the instructions in the 'Read Me', which were very clear.
Unfortunately there are no data shown in my dashboard.
Regularly an error message pops up saying 'Annotation query failed - Query missing in annotation definition'.

I can see the variables in Grafana (Synology Docker), so there is a link between Synology (actually Xpenology self-built, DSM 5.2) and the InfluxDB running as a Synology-Docker.

Somewhere in the read-me there is a reference to the MIB files. Do I need to do anything with them?

I also checked with the Paessler SNMP tester tool and as far as I can see all works fine.

Anyone an idea what I did wrong?

**Comment by abl73** [comment] 2020-07-13 21:48
A quick update. I tried a few things and now Grafana shows the following error:
'Error parsing query: found <<name of my NAS>>, expected regex at line 1, char 351'

**Comment by kernelkaribou** [comment] 2020-07-30 00:54
This is something I am not that confident in as to the cause. I noticed that the template was using annotations as a configuration that I never defined. This template was created some time ago so it may have created issues with newer versions of Grafana. I removed the annotations from the template and confirmed it imports correctly. Hopefully that addresses the issues.

**Comment by kernelkaribou** [comment] 2020-07-30 22:53
Closing as multiple errors I was seeing were fixed with the latest version of the template including the one reported here.

**Closed by kernelkaribou** 2020-07-30 22:53 UTC
